apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  creationTimestamp: null
  name: gotk-system
  namespace: gotk-system
spec:
  interval: 10m0s
  path: ./clusters/01
  prune: true
  sourceRef:
    kind: GitRepository
    name: gotk-system
  validation: client
status: {}
